# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 577)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1041, 46))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gridLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(700, 22))
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setPlaceholderText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 480, 1041, 61))
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1041, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1066, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuSave_as = QtWidgets.QMenu(self.menuBar)
        self.menuSave_as.setObjectName("menuSave_as")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setObjectName("menuOption")
        self.menuSort = QtWidgets.QMenu(self.menuOption)
        self.menuSort.setObjectName("menuSort")
        self.menuSort_By_Date = QtWidgets.QMenu(self.menuSort)
        self.menuSort_By_Date.setObjectName("menuSort_By_Date")
        self.menuSort_By_Shares = QtWidgets.QMenu(self.menuSort)
        self.menuSort_By_Shares.setObjectName("menuSort_By_Shares")
        self.menuSort_By_Likes = QtWidgets.QMenu(self.menuSort)
        self.menuSort_By_Likes.setObjectName("menuSort_By_Likes")
        self.menuSort_By_Comments = QtWidgets.QMenu(self.menuSort)
        self.menuSort_By_Comments.setObjectName("menuSort_By_Comments")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAscending = QtWidgets.QAction(MainWindow)
        self.actionAscending.setObjectName("actionAscending")
        self.actionDescendinf = QtWidgets.QAction(MainWindow)
        self.actionDescendinf.setObjectName("actionDescendinf")
        self.actionAscending_2 = QtWidgets.QAction(MainWindow)
        self.actionAscending_2.setObjectName("actionAscending_2")
        self.actionAscending_3 = QtWidgets.QAction(MainWindow)
        self.actionAscending_3.setObjectName("actionAscending_3")
        self.actionAscending_4 = QtWidgets.QAction(MainWindow)
        self.actionAscending_4.setObjectName("actionAscending_4")
        self.actionDescending = QtWidgets.QAction(MainWindow)
        self.actionDescending.setObjectName("actionDescending")
        self.actionDescending_2 = QtWidgets.QAction(MainWindow)
        self.actionDescending_2.setObjectName("actionDescending_2")
        self.actionDescending_3 = QtWidgets.QAction(MainWindow)
        self.actionDescending_3.setObjectName("actionDescending_3")
        self.menuSave_as.addAction(self.actionSave)
        self.menuSort_By_Date.addSeparator()
        self.menuSort_By_Date.addAction(self.actionAscending)
        self.menuSort_By_Date.addAction(self.actionDescendinf)
        self.menuSort_By_Shares.addAction(self.actionAscending_2)
        self.menuSort_By_Shares.addAction(self.actionDescending)
        self.menuSort_By_Likes.addAction(self.actionAscending_3)
        self.menuSort_By_Likes.addAction(self.actionDescending_2)
        self.menuSort_By_Comments.addAction(self.actionAscending_4)
        self.menuSort_By_Comments.addAction(self.actionDescending_3)
        self.menuSort.addAction(self.menuSort_By_Date.menuAction())
        self.menuSort.addAction(self.menuSort_By_Shares.menuAction())
        self.menuSort.addAction(self.menuSort_By_Likes.menuAction())
        self.menuSort.addAction(self.menuSort_By_Comments.menuAction())
        self.menuOption.addAction(self.menuSort.menuAction())
        self.menuBar.addAction(self.menuSave_as.menuAction())
        self.menuBar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Facebook Scrapper"))
        self.label.setText(_translate("MainWindow", "ID  :"))
        self.radioButton_2.setText(_translate("MainWindow", "Post Limit"))
        self.radioButton_3.setText(_translate("MainWindow", "Day Limit"))
        self.radioButton.setText(_translate("MainWindow", "Unlimited Scrap"))
        self.checkBox.setText(_translate("MainWindow", "Advance Scrap"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.menuSave_as.setTitle(_translate("MainWindow", "File"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuSort.setTitle(_translate("MainWindow", "Sort"))
        self.menuSort_By_Date.setTitle(_translate("MainWindow", "Sort By Date"))
        self.menuSort_By_Shares.setTitle(_translate("MainWindow", "Sort By Shares"))
        self.menuSort_By_Likes.setTitle(_translate("MainWindow", "Sort By Likes"))
        self.menuSort_By_Comments.setTitle(_translate("MainWindow", "Sort By Comments"))
        self.actionSave.setText(_translate("MainWindow", "Save as CSV"))
        self.actionAscending.setText(_translate("MainWindow", "Ascending"))
        self.actionDescendinf.setText(_translate("MainWindow", "Descending"))
        self.actionAscending_2.setText(_translate("MainWindow", "Ascending"))
        self.actionAscending_3.setText(_translate("MainWindow", "Ascending"))
        self.actionAscending_4.setText(_translate("MainWindow", "Ascending"))
        self.actionDescending.setText(_translate("MainWindow", "Descending"))
        self.actionDescending_2.setText(_translate("MainWindow", "Descending"))
        self.actionDescending_3.setText(_translate("MainWindow", "Descending"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
